# Generated by Django 3.2.7 on 2021-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
