# Generated by Django 3.2.7 on 2021-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default='', max_length=13),
        ),
    ]
