# Generated by Django 3.2.7 on 2021-11-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211127_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Twitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Website',
            new_name='website',
        ),
    ]
