# Generated by Django 3.2.7 on 2021-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211129_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default='https://github.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/feed/', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='https://twitter.com/?lang=en', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(default='https://iiitdwd.ac.in/', max_length=100),
        ),
    ]
